# Generated by Django 5.2 on 2025-05-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_fill_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
